# SwiftLint Configuration for Health Exporter
# Privacy-focused, security-conscious linting rules

# Paths to include/exclude
included:
  - HealthExporter/
excluded:
  - HealthExporter/Preview Content/
  - .build/
  - Carthage/
  - Pods/

# Rules to enable
opt_in_rules:
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate
  - yoda_condition

# Rules to disable
disabled_rules:
  - todo # We'll handle TODOs in CI differently

# Custom rule configurations
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 60
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 800

cyclomatic_complexity:
  warning: 8
  error: 12

# Custom rules for health data privacy
custom_rules:
  no_print_statements:
    name: "No Print Statements in Release"
    regex: '^\s*print\s*\('
    message: "Use proper logging instead of print statements"
    severity: warning
    
  no_hardcoded_strings:
    name: "No Hardcoded API Keys or Secrets"
    regex: '(api_key|secret|password|token)\s*[=:]\s*"[^"]*"'
    message: "Potential hardcoded secret detected"
    severity: error
    
  health_data_comment:
    name: "Health Data Handling Comment"
    regex: 'HKSample|HealthKit'
    message: "Ensure health data handling follows privacy guidelines"
    severity: warning

# Identifier naming rules
identifier_name:
  min_length: 2
  max_length: 60
  excluded:
    - id
    - url
    - key

type_name:
  min_length: 3
  max_length: 40
  excluded:
    - URL

# Force unwrapping configuration
force_unwrapping:
  severity: error

# File header configuration
file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*\.swift
                    \/\/  Health Exporter
                    \/\/
                    \/\/  Created by .* on .*\.
                    \/\/

# Reporter configuration
reporter: "xcode"